export type PartType = typeof PARTS[number];
export const PARTS = [
  "steel_pipe",
  "steel_beam",
  "steel_ingot",
  "iron_ingot",
  "recinforced_plate",
  "screw",
  "industrial_beam",
  "iron_plate",
  "modular_frame",
  "heavy_modular_frame",
  "computer",
  "rubber",
  "quick_wire",
  "circut_board",
  "plastic",
  "caterium_ingot",
  "copper_ingot",
] as const;
