export type Part = typeof PARTS[number];
export const PARTS = [
  "steel_pipe",
  "steel_beam",
  "industrial_beam",
  "iron_rod",
  "iron_plate",
  "screw",
  "recinforced_plate",
  "modular_frame",
  "heavy_modular_frame",
  "computer",
  "circuit_board",
  "rubber",
  "plastic",
  "wire",
  "copper_sheet",
  "quickwire",
  "steel_ingot",
  "iron_ingot",
  "caterium_ingot",
  "copper_ingot",
  "high_speed_connector",
  "empty_canister",
  "modular_engine",
  "nuclear_fuel_rod",
  "crystal_oscillator",
  "battery",
  "packaged_fuel",
  "rotor",
  "electromagnetic_control_rod",
  "polymer_resin",
  "steel_plate",
  "uranium_cell",
  "packaged_liquid_biofuel",
  "plastic",
  "ficsmas_tree_branch",
  "biofuel",
  "adaptive_control_unit",
  "smart_plating",
  "ficsmas_gift",
  "solid_biofuel",
  "alclad_aluminum_sheet",
  "supercomputer",
  "steel_pipe",
  "ficsmas_ornament_bundle",
  "packaged_heavy_oil_residue",
  "snowball_pile",
  "heat_sink",
  "motor",
  "snowball",
  "candy_cane",
  "copper_ficsmas_ornament",
  "stator",
  "blue_ficsmas_ornament",
  "cable",
  "automated_wiring",
  "turbo_motor",
  "ai_limiter",
  "radio_control_unit",
  "nobelisk",
  "ficsmas_decoration",
  "compacted_coal",
  "quartz_crystal",
  "silica",
  "black_powder",
  "aluminum_ingot",
  "versatile_framework",
  "ficsmas_bow",
  "packaged_turbofuel",
  "red_ficsmas_ornament",
  "uranium_pellet",
  "petroleum_coke",
  "aluminum_scrap",
  "iron_ficsmas_ornament",
  "concrete",
  "alumina_solution",
] as const;

export const partTypeReadable: {
  [key in Part]: string;
} = {
  steel_beam: "Steel Beam",
  steel_pipe: "Steel Pipe",
  steel_ingot: "Steel Ingot",
  iron_ingot: "Iron Ingot",
  heavy_modular_frame: "Heavy Modular Frame",
  industrial_beam: "Industrial Beam",
  iron_plate: "Iron Plate",
  modular_frame: "Modular Frame",
  recinforced_plate: "Recinforced Plate",
  screw: "Screw",
  caterium_ingot: "Caterium Ingot",
  circuit_board: "Circut Board",
  computer: "Computer",
  copper_ingot: "Copper Ingot",
  plastic: "Plastic",
  quickwire: "Quickwire",
  rubber: "Rubber",
  concrete: "Concrete",
  cable: "Cable",
  copper_sheet: "Copper Sheet",
  wire: "Wire",
  iron_rod: "Iron Rod",
  adaptive_control_unit: "Adaptive Control Unit",
  ai_limiter: "AI Limiter",
  alclad_aluminum_sheet: "Alclad Aluminum Sheet",
  aluminum_ingot: "Aluminum Ingot",
  aluminum_scrap: "Aluminum Scrap",
  high_speed_connector: "High Speed Connector",
  empty_canister: "Empty Canister",
  modular_engine: "Modular Enginer",
  nuclear_fuel_rod: "Nuclear Fuel Rod",
  crystal_oscillator: "Crystal Oscillator",
  battery: "Battery",
  packaged_fuel: "Packaged Fuel",
  rotor: "Rotor",
  electromagnetic_control_rod: "Electromagnetic Control Rod",
  polymer_resin: "Polymer Resin",
  steel_plate: "Steel Plate",
  uranium_cell: "Uranium Cell",
  packaged_liquid_biofuel: "Packaged Liquid Biofuel",
  ficsmas_tree_branch: "Ficmas Tree Branch",
  biofuel: "Boifuel",
  smart_plating: "Smart Plating",
  ficsmas_gift: "Ficmas Gift",
  solid_biofuel: "Solid Biofuel",
  supercomputer: "Supercomputer",
  ficsmas_ornament_bundle: "Ficmas Ornament Bundle",
  packaged_heavy_oil_residue: "",
  snowball_pile: "Snowball Pile",
  heat_sink: "Heatsink",
  motor: "Motor",
  snowball: "Snowball",
  candy_cane: "Candy Cane",
  copper_ficsmas_ornament: "Copper Ficmas Ornament",
  stator: "Stator",
  blue_ficsmas_ornament: "Blue Ficmas Ornament",
  automated_wiring: "Automated Wiring",
  turbo_motor: "Turbo Motor",
  radio_control_unit: "Radio Control Unit",
  nobelisk: "Nobelisk",
  ficsmas_decoration: "Ficmas Decoration",
  compacted_coal: "Compacted Coal",
  quartz_crystal: "Quartz Crystal",
  silica: "Silica",
  black_powder: "Black Poweder",
  versatile_framework: "Versatile Framework",
  ficsmas_bow: "Ficmas Bow",
  packaged_turbofuel: "Packaged Turbofuel",
  red_ficsmas_ornament: "Ficmas Ornament",
  uranium_pellet: "Uranium Pellet",
  petroleum_coke: "Petroleum Coke",
  iron_ficsmas_ornament: "Iron Ficmas Ornament",
  alumina_solution: "Alumina Solution",
};

export const isPart = (part: any): part is Part => {
  return PARTS.includes(part);
};
